# Generated by Django 5.2.11 on 2026-08-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='projects/')),
                ('category', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('API', 'API'), ('ML', 'Machine Learning'), ('OTHER', 'Other')], max_length=20)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('completed_date', models.DateField()),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tech_stack', models.ManyToManyField(related_name='projects', to='core.skill')),
            ],
            options={
                'ordering': ['-completed_date'],
            },
        ),
    ]
